version: "3.9"

services:
  plexrelay:
    image: ghcr.io/oliverp/plexrelay:latest  # We'll need to set this up
    container_name: plexrelay-bridge
    ports:
      - "8880:8880"
    environment:
      - PPV_AUTH_TOKEN=your_auth_token_here
    restart: unless-stopped

  xteve:
    image: linuxserver/xteve:latest
    container_name: xteve
    environment:
      - PUID=568  # change to match your user ID
      - PGID=568  # change to match your group ID
      - TZ=America/Vancouver  # change to your timezone
    volumes:
      - ./xteve:/config
    ports:
      - "34400:34400"  # xTeVe web interface
    restart: unless-stopped
    depends_on:
      - plexrelay