version: "3.9"

services:
  plexrelay:
    image: ghcr.io/timelessfun/plexrelay:latest
    container_name: plexrelay-bridge
    ports:
      - "8880:8880"
    volumes:
      - /mnt/<yourpool>/plexrelay:/app/data
    environment:
      - PPV_AUTH_TOKEN=your_auth_token_here
      - TZ=America/Vancouver  # change to your timezone
    restart: unless-stopped

  xteve:
    image: alturismo/xteve:latest
    container_name: xteve
    environment:
      - PUID=568  # change to match your user ID
      - PGID=568  # change to match your group ID
      - TZ=America/Vancouver  # change to your timezone
    volumes:
      - /mnt/<yourpool>/xteve:/config
    ports:
      - "34400:34400"  # xTeVe web interface
    restart: unless-stopped
    depends_on:
      - plexrelay